# These settings don't really work. They're used to troubleshoot the pipeline of
# operations because the real settings take much longer to run.

[freqs.analyze]
delta_t_ms = 40
freq_step = 2

[freqs.bistable]
input_bound = [0.005, 5.0]
lowpass = 1.5
lowpass_order = 3

[scales.analyze]
scales_cycoct = [0.5,2.0,8.0]
bandonly = true

[scales.bistable]
input_bound = [0.005, 0.1]
lowpass = 1.5
lowpass_order = 3

[rates]
rates_Hz = [2, 8, 32]
freq_limits_Hz = [400.0, 800.0]
bandonly = true

[nmf]
ncomponents = 2
window_ms = 100
delta_ms = 200
skipframes = 0
maxiter = 20
tol = 1e-1

[track.analyze]
time_constants_s = [8.0,16.0]
max_sources = 2
source_prior_sds = [6.0,7.0,9.0]
source_prior_N = 4
freq_prior_bias = 0
freq_prior_N = 2

[track.bistable]
normalize_start_s = 0.5
input_bound = [0.0, 0.75]
lowpass = 1.5
lowpass_order = 3

[percept_lengths]
window_ms = 500
delta_ms = 500
min_length_ms = 750
threshold = 2.1
bandwidth_threshold = 0.25

